### ISSUE TITLE
US 02.01.01

### ISSUE THREAD

**Issue by bpaul2** [CMPUT301F23T01/Sigma-Blue#12]
As an owner, I want to see a list of my items

# Requirements

- Create list adapter for a list of items

# Checklist

- [x] Make BaseActivity class #38 
- [x] Create the ActivityLauncher Class for creating new activities for a return #41 
- [x] Make the ItemList class that will be used to store Items. Dependent on #8 for the element.
- [x] Make the ItemListAdapter Class #40
- [x] The ViewListActivity has to be completed.
- [x] ItemDB must be implemented #30

**Comment by waridh** [comment]
we are able to view the list of items. Thanks!
